## Задание 1

In [1]:
import pandas as pd

In [3]:
df_ratings = pd.read_csv('ratings.csv')
df_ratings.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [4]:
def rating_class(row):
  rating = ''

  if row <= 2:
    rating = 'низкий рейтинг'
  elif row <= 4:
    rating = 'средний рейтинг'
  elif row == 4.5 or row == 5:
    rating = 'высокий рейтинг'

  return rating

In [5]:
df_ratings['class'] = df_ratings['rating'].apply(rating_class)
df_ratings.head()

   userId  movieId  rating   timestamp            class
0       1       31     2.5  1260759144  средний рейтинг
1       1     1029     3.0  1260759179  средний рейтинг
2       1     1061     3.0  1260759182  средний рейтинг
3       1     1129     2.0  1260759185   низкий рейтинг
4       1     1172     4.0  1260759205  средний рейтинг

## Задание 2

In [6]:
df_keywords = pd.read_csv('keywords.csv')
df_keywords.head()

         keyword     shows
0             вк  64292779
1  одноклассники  63810309
2          порно  41747114
3           ютуб  39995567
4      вконтакте  21014195

In [7]:
geo_data = { 'Центр': ['москва', 'тула', 'ярославль'],
               'Северо-Запад': ['петербург', 'псков', 'мурманск'],
               'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск'] }

def geo_class(row):
  region = 'undefined'

  for key, value in geo_data.items():
    for r in row.lower().split(' '):
      if r in value:
        region = key
        break

  return region

In [8]:
df_keywords['region'] = df_keywords['keyword'].apply(geo_class)
df_keywords.region.value_counts()

undefined         99406
Центр               382
Северо-Запад        148
Дальний Восток       64
Name: region, dtype: int64

## Задание 3

In [9]:
import re

In [10]:
df_ratings = pd.read_csv('ratings.csv')
df_ratings.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [11]:
df_movies = pd.read_csv('movies.csv')
df_movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [12]:
years = range(1950,2011)

def production_year(row):
  res = re.findall(r"[0-9]{4}", row)

  if res != []:
    if int(res[0]) in years:
      return int(res[0])

  return 1900

In [20]:
df_movies['year'] = df_movies['title'].apply(production_year)
df_movies.head()

,movieId,title,genres,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men (1995),Comedy|Romance,1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II (1995),Comedy,1995

In [21]:
df_ratings = df_ratings.groupby(['movieId']).agg({'rating': 'sum'}).reset_index()
df_ratings.head()

   movieId  rating
0        1   956.5
1        2   364.0
2        3   186.5
3        4    31.0
4        5   183.0

In [28]:
df_merge = df_movies.merge(df_ratings, on='movieId').sort_values('rating', ascending=False)
df_merge.head(-5)

,movieId,title,genres,year,rating
284,318,"Shawshank Redemption, The (1994)",Crime|Drama,1994,1395.5
321,356,Forrest Gump (1994),Comedy|Drama|Romance|War,1994,1382.5
266,296,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,1994,1379.0
525,593,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller,1991,1258.0
232,260,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,1977,1228.5
...,...,...,...,...,...
3673,4684,Worth Winning (1989),Comedy,1989,0.5
7016,61465,Bangkok Dangerous (2008),Action|Crime|Thriller,2008,0.5
8791,129250,Superfast! (2015),(no genres listed),1900,0.5
1742,2191,"Merry War, A (1997)",Comedy,1997,0.5
5145,7448,Envy (2004),Comedy,2004,0.5